---
title: "getting data"
author: "Mariia Koliada"
date: "10 03 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

install.packages("googlesheets")
library(googlesheets)

gs_auth(new_user = TRUE)
# after will get autorization code

gs_ls()

#open some sheet 
survey_sheet <- gs_title("Nasa")

survey_data <- gs_read(survey_sheet)

my_response <- c("09-26-2018",	"Mariia Koliada",	"m007@gmail.com",	"Lviv",	"Checked In",	1,	1, 3)
gs_add_row(survey_sheet, input = my_response)

gs_edit_cells(survey_sheet, anchor = "H68", input = 100)

import data directly to google sheet 
=importData("https://raw.githubusercontent.com/datasets/gdp/master/data/gdp.csv")

## Data from internet
## Install packages
install.packages(c("httr", "rvest", "jsonlite"))

## load package
library(httr)
library(dplyr)
 	
## Save GitHub username as variable
username <- 'janeeverydaydoe'

## Save base endpoint as variable
url_git <- 'https://api.github.com/'

## Construct API request
api_response <- GET(url = paste0(url_git, 'users/', username, '/repos'))

## load package
library(rvest)

## provide URL
courses <- read_html("https://www.datacamp.com/tracks/data-scientist-with-r")

## Get Courses
courses %>%
html_nodes(".dc-u-fx-center , .course-block__title")%>%
html_text()

courses

write.csv(courses, file = "MDataCampcouse.csv")
class(courses)

## load package
library(rvest)

## provide URL
films <- read_html("https://movies.platfor.ma/girl-power")

## Get movies
films %>%
html_nodes(".loaded , .t-container.t-align_center , span")%>%
html_text()



films





